version: "3"
services:
  test:
    build: .
    ports:
      - "4400"
    container_name: gfw-forms-test
    environment:
      PORT: 4400
      NODE_ENV: test
      CT_URL: http://mymachine:9000
      API_VERSION: v1
      CT_REGISTER_MODE: auto
      MONGO_PORT_27017_TCP_ADDR: mongo
      TARGET_SHEET_ID: TARGET_SHEET_ID
      LOCAL_URL: http://gfw-forms:4400
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      FASTLY_ENABLED: "false"
    command: test
    depends_on:
      - mongo

  mongo:
    image: mongo:3.4
    command: --smallfiles
    ports:
      - "27017"
