apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: fw
  name: forms
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: forms
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
